import{i}from"./assets/vendor-17o45ynk.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const u="https://pixabay.com/api/",f="11281296-1f4fc3f6c48856d743f19a161";async function d(o,t=1){const s=`${u}?key=${f}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=12&page=${t}`;try{const n=await fetch(s);if(!n.ok)throw new Error("Failed to fetch images");return await n.json()}catch(n){console.error("Error:",n)}}function y(o){const t=document.querySelector(".gallery"),s=o.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p><strong>Likes:</strong> ${e.likes}</p>
          <p><strong>Views:</strong> ${e.views}</p>
          <p><strong>Comments:</strong> ${e.comments}</p>
          <p><strong>Downloads:</strong> ${e.downloads}</p>
        </div>
      </a>`).join("");t.innerHTML=s,new SimpleLightbox(".gallery a").refresh()}function g(){const o=document.querySelector(".gallery");o.innerHTML=""}const l=document.querySelector("#search-form"),c=document.querySelector(".loader");l.addEventListener("submit",async o=>{o.preventDefault();const t=o.currentTarget.elements.searchQuery.value.trim();if(!t){i.error({title:"Error",message:"Please enter a search query!"});return}g(),c.style.display="block";try{const s=await d(t);s.hits.length===0?i.warning({title:"No results",message:"Sorry, there are no images matching your search query."}):y(s.hits)}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{c.style.display="none",m()}});function m(){l.reset()}
//# sourceMappingURL=index.js.map
