import{S as u,i}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const f="https://pixabay.com/api/",d="11281296-1f4fc3f6c48856d743f19a161";async function g(s,o=1){const n=`${f}?key=${d}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&per_page=12&page=${o}`;try{const r=await fetch(n);if(!r.ok)throw new Error("Failed to fetch images");return await r.json()}catch(r){console.error("Error:",r)}}function h(s){const o=document.querySelector(".gallery");o.innerHTML=s.map(r=>`
      <a href="${r.largeImageURL}" class="gallery-item">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        <div class="info">
          <p><strong>Likes:</strong> ${r.likes}</p>
          <p><strong>Views:</strong> ${r.views}</p>
          <p><strong>Comments:</strong> ${r.comments}</p>
          <p><strong>Downloads:</strong> ${r.downloads}</p>
        </div>
      </a>`).join(""),new u(".gallery a").refresh()}function m(){const s=document.querySelector(".gallery");s.innerHTML=""}const c=document.querySelector("#search-form"),l=document.querySelector(".loader");c.addEventListener("submit",async s=>{s.preventDefault();const o=s.currentTarget.elements.searchQuery.value.trim();if(!o){i.error({title:"Error",message:"Please enter a search query!"});return}m(),p();try{const n=await g(o);n.hits.length===0?i.warning({title:"No results",message:"Sorry, there are no images matching your search query."}):h(n.hits)}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{L(),y()}});function y(){c.reset()}function p(){l.classList.remove("hidden")}function L(){l.classList.add("hidden")}
//# sourceMappingURL=index.js.map
